language: csharp
mono: none
dotnet: 1.0.1
dist: trusty
solution: Ibsys2/Ibsys2.sln


install:
  - nuget restore Ibsys2.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:    # the following commands are just examples, use whatever your build process requires
  - ./build.sh
  - ./test.sh
  - grep "Test Results" build.log