dist: trusty
sudo: required
os: linux
git:
  depth: 3
language: csharp
dotnet: 1.0.1
mono: none
env: DOTNETCORE=1

install:
    - dotnet restore Ibsys2
before_script:
    - chmod +x *.sh
script:
- ./build.sh