language: csharp
mono: none
dotnet: 1.0.1
dist: trusty
solution: Ibsys2/Ibsys2.sln


script:    # the following commands are just examples, use whatever your build process requires
  - ./build.sh
  - ./test.sh
  - grep "Test Results" build.log